In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr

[[7605, 7252, 9272, 2771],
 [7605, 7252, 9272, 5190],
 [9922, 8153, 8722, 9223, 8620],
 [9922, 8153, 8722, 9223, 5719],
 [8596, 7605, 1003, 9272, 6466],
 [1832, 2533, 3843, 9223]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7605 7252 9272 2771]
 [   0    0    0    0 7605 7252 9272 5190]
 [   0    0    0 9922 8153 8722 9223 8620]
 [   0    0    0 9922 8153 8722 9223 5719]
 [   0    0    0 8596 7605 1003 9272 6466]
 [   0    0    0    0 1832 2533 3843 9223]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

c:\Users\sanja\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


array([[[-0.02848437,  0.03647865,  0.04584643,  0.04817872,
          0.02578442,  0.03584277,  0.02135699, -0.04950162,
          0.00069207, -0.02055982],
        [-0.02848437,  0.03647865,  0.04584643,  0.04817872,
          0.02578442,  0.03584277,  0.02135699, -0.04950162,
          0.00069207, -0.02055982],
        [-0.02848437,  0.03647865,  0.04584643,  0.04817872,
          0.02578442,  0.03584277,  0.02135699, -0.04950162,
          0.00069207, -0.02055982],
        [-0.02848437,  0.03647865,  0.04584643,  0.04817872,
          0.02578442,  0.03584277,  0.02135699, -0.04950162,
          0.00069207, -0.02055982],
        [-0.02714059, -0.03740674,  0.04365081,  0.02727241,
         -0.02475992,  0.00300722,  0.03638062,  0.01881573,
         -0.01026747, -0.02165636],
        [ 0.02277626, -0.00896132,  0.00535624, -0.0225667 ,
          0.0357349 , -0.01036209, -0.00489389, -0.03626021,
         -0.02038883,  0.00041186],
        [ 0.00517782, -0.02173023, -0.02231047,  0.0

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (6, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7605, 7252, 9272, 2771], dtype=int32)